CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  category VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO products (name, description, price)
VALUES
  ("Apple iPhone XR", "The latest iPhone XR with a 6.1-inch LCD display", 799.99),
  ("Samsung Galaxy S21", "The latest Samsung Galaxy S21 with a 6.2-inch AMOLED display", 799.99),
  ("Google Pixel 5", "The latest Google Pixel 5 with a 6-inch OLED display", 699.99),
  ("OnePlus 9 Pro", "The latest OnePlus 9 Pro with a 6.7-inch AMOLED display", 899.99),
  ("Sony Xperia 5 III", "The latest Sony Xperia 5 III with a 6.1-inch OLED display", 799.99),
  ("Apple iPad Pro", "The latest iPad Pro with an 11-inch Liquid Retina display", 799.99),
  ("Microsoft Surface Laptop 4", "The latest Microsoft Surface Laptop 4 with an 13.5-inch PixelSense display", 999.99),
  ("Dell XPS 13", "The latest Dell XPS 13 with a 13.3-inch InfinityEdge display", 999.99),
  ("HP Spectre x360", "The latest HP Spectre x360 with a 13.3-inch Full HD display", 899.99),
  ("Acer Swift 5", "The latest Acer Swift 5 with a 14-inch Full HD display", 799.99),
  ("Asus ROG Zephyrus G14", "The latest Asus ROG Zephyrus G14 with a 14-inch Full HD display", 1,499.99),
  ("Lenovo ThinkPad X1 Carbon", "The latest Lenovo ThinkPad X1 Carbon with a 14-inch Full HD display", 1,199.99),
  ("Razer Blade Pro 17", "The latest Razer Blade Pro 17 with a 17.3-inch 4K display", 2,999.99),
  ("Alienware m15 R6", "The latest Alienware m15 R6 with a 15.6-inch Full HD display", 1,799.99),
  ("MSI GS75 Stealth", "The latest MSI GS75 Stealth with a 17.3-inch Full HD display", 1,499.99),
  ("Apple MacBook Air M2", "The latest MacBook Air M2 with a 13.3-inch Retina display", 999.99),
  ("Apple MacBook Pro M1", "The latest MacBook Pro M1 with a 16-inch Retina display", 1,999.99),
  ("Apple iMac Pro", "The latest iMac Pro with a 27-inch Retina 5K display", 4,999.99),
  ("Apple Mac Mini M1", "The latest Mac Mini M1 with the M1 chip", 699.99),
  ("Bose QuietComfort 35 II", "The latest Bose QuietComfort 35 II wireless headphones", 349.99),
  ("Sony WH-1000XM4", "The latest Sony WH-1000XM4 wireless headphones", 349.99),
  ("Bowers & Wilkins PX7", "The latest Bowers & Wilkins PX7 wireless headphones", 399.99),
  ("Sennheiser Momentum 3", "The latest Sennheiser Momentum 3 wireless headphones", 399.99),
  ("Beats Solo Pro", "The latest Beats Solo Pro wireless headphones", 299.99),
  ("Bose SoundLink Mini II", "The latest Bose SoundLink Mini II portable speaker", 199.99),
  ("JBL Flip 5", "The latest JBL Flip 5 portable speaker", 99.99),
  ("UE Boom 3", "The latest UE Boom 3 portable speaker", 149.99),
  ("Sony SRS-X9", "The latest Sony SRS-X9 portable speaker", 249.99),
  ("Bose SoundTouch 10", "The latest Bose SoundTouch 10 wireless speaker", 199.99),
  ("Sonos One", "The latest Sonos One smart speaker", 199.99),
  ("Google Nest Mini", "The latest Google Nest Mini smart speaker", 49.99),
  ("Amazon Echo Dot", "The latest Amazon Echo Dot smart speaker", 49.99),
  ("Apple HomePod mini", "The latest Apple HomePod mini smart speaker", 99.99),
  ("Harman Kardon Invoke", "The latest Harman Kardon Invoke smart speaker", 199.99),
  ("Lenovo Smart Display", "The latest Lenovo Smart Display with Google Assistant", 199.99),
  ("JBL Link View", "The latest JBL Link View smart display with Google Assistant", 249.99),
  ("Amazon Echo Show", "The latest Amazon Echo Show smart display with Alexa", 229.99),
  ("Google Nest Hub", "The latest Google Nest Hub smart display with Google Assistant", 129.99),
  ("Fitbit Charge 4", "The latest Fitbit Charge 4 fitness tracker", 149.99),
  ("Garmin vivosmart 4", "The latest Garmin vivosmart 4 fitness tracker", 129.99),
  ("Samsung Galaxy Fit 2", "The latest Samsung Galaxy Fit 2 fitness tracker", 99.99),
  ("Apple Watch Series 6", "The latest Apple Watch Series 6 with cellular connectivity", 399.99),
  ("Fitbit Versa 3", "The latest Fitbit Versa 3 smartwatch", 229.99),
  ("Garmin Forerunner 245", "The latest Garmin Forerunner 245 GPS running watch", 299.99),
  ("Samsung Galaxy Watch Active 2", "The latest Samsung Galaxy Watch Active 2 smartwatch", 229.99),
  ("Apple AirPods Pro", "The latest Apple AirPods Pro with active noise cancellation", 249.99),
  ("Jabra Elite 75t", "The latest Jabra Elite 75t wireless earbuds", 149.99),
  ("Sony WF-1000XM4", "The latest Sony WF-1000XM4 wireless earbuds", 229.99),
  ("Bose QuietComfort Earbuds", "The latest Bose QuietComfort Earbuds wireless earbuds", 279.99),
  ("Sennheiser Momentum True Wireless 2", "The latest Sennheiser Momentum True Wireless 2 earbuds", 299.99)
;
